### ISSUE TITLE
Fix GUI

### ISSUE THREAD

**Issue by Xeckt** [Xeckt/alley#4]
Right now there is one issue with the GUI in it's current state - when you resize the MainWindow for adding / removing mods, the columns showing data about the mod do not resize with it, so you end up with lots of blank space.

It needs to either dynamically resize or we set a fixed height and width on the Window. I like dynamic resizing so that the user experience is tailored and people with bigger/smaller monitors do not run into scaling issues.

**Comment by LoulouNoLegend** [comment]
**Let's go it's fixed**

**Comment by Xeckt** [comment]
True! I forgot to close this issue. Closed by commit: e3d917accd3843c9629633c11511d70dfcd5263f
